### ISSUE TITLE
Error NoClassDefFoundError slf4j

### ISSUE THREAD

**Issue by GeCol1** [fuinorg/ext4logback#1]
Hello,

I've tried the example of your lib but when in the LogbakcStandalone() init() method, I have this error:
```
Caused by: java.lang.NoClassDefFoundError: org/slf4j/event/Level
	at org.fuin.ext4logback.NewLogConfigFileParams.<init>(NewLogConfigFileParams.java:46)
```
with this code:
```java
new LogbackStandalone().init(new File(logFilePath.toString() + "/logback.xml"), new NewLogConfigFileParams("com.packge", "logfile"));
```
and here is an extract of my pom:
```xml
<dependency>
            <groupId>ch.qos.logback</groupId>
            <artifactId>logback-classic</artifactId>
            <version>1.2.3</version>
        </dependency>
        <dependency>
            <groupId>org.fuin</groupId>
            <artifactId>ext4logback</artifactId>
            <version>0.2.0</version>
        </dependency>
```
any idea?

**Comment by michael-schnell** [comment]
I wasn't able to reproduce this error. I added a simple example project here: 
https://github.com/fuinorg/ext4logback/tree/master/example
Maybe you can try it and see if you get the same error.

**Comment by GeCol1** [comment]
Thanks for the sample but I have the same error, so probably from my config but I don't see what's wrong...
If I have time, I'll check with the version from github and not mavencentral, maybe a diff there?

```
$ mvn exec:java
[INFO] Scanning for projects...
Downloading: https://dl.bintray.com/jerady/maven/org/codehaus/mojo/exec-maven-plugin/1.6.0/exec-maven-plugin-1.6.0.pom
Downloading: https://repo.maven.apache.org/maven2/org/codehaus/mojo/exec-maven-plugin/1.6.0/exec-maven-plugin-1.6.0.pom
Downloaded: https://repo.maven.apache.org/maven2/org/codehaus/mojo/exec-maven-plugin/1.6.0/exec-maven-plugin-1.6.0.pom (13 kB at 49 kB/s)
Downloading: https://dl.bintray.com/jerady/maven/org/codehaus/mojo/exec-maven-plugin/1.6.0/exec-maven-plugin-1.6.0.jar
Downloading: https://repo.maven.apache.org/maven2/org/codehaus/mojo/exec-maven-plugin/1.6.0/exec-maven-plugin-1.6.0.jar
Downloaded: https://repo.maven.apache.org/maven2/org/codehaus/mojo/exec-maven-plugin/1.6.0/exec-maven-plugin-1.6.0.jar (58 kB at 434 kB/s)
[INFO]
[INFO] ------------------------------------------------------------------------
[INFO] Building ext4logback-example 0.1.0-SNAPSHOT
[INFO] ------------------------------------------------------------------------
Downloading: https://dl.bintray.com/jerady/maven/org/fuin/ext4logback/0.2.0/ext4logback-0.2.0.pom
Downloading: https://repo.maven.apache.org/maven2/org/fuin/ext4logback/0.2.0/ext4logback-0.2.0.pom
Downloaded: https://repo.maven.apache.org/maven2/org/fuin/ext4logback/0.2.0/ext4logback-0.2.0.pom (0 B at 0 B/s)
Downloading: https://dl.bintray.com/jerady/maven/org/fuin/pom/1.4.0/pom-1.4.0.pom
Downloading: https://repo.maven.apache.org/maven2/org/fuin/pom/1.4.0/pom-1.4.0.pom
Downloaded: https://repo.maven.apache.org/maven2/org/fuin/pom/1.4.0/pom-1.4.0.pom (0 B at 0 B/s)
Downloading: https://dl.bintray.com/jerady/maven/ch/qos/logback/logback-classic/1.1.8/logback-classic-1.1.8.pom
Downloading: https://repo.maven.apache.org/maven2/ch/qos/logback/logback-classic/1.1.8/logback-classic-1.1.8.pom
Downloaded: https://repo.maven.apache.org/maven2/ch/qos/logback/logback-classic/1.1.8/logback-classic-1.1.8.pom (0 B at 0 B/s)
Downloading: https://dl.bintray.com/jerady/maven/ch/qos/logback/logback-parent/1.1.8/logback-parent-1.1.8.pom
Downloading: https://repo.maven.apache.org/maven2/ch/qos/logback/logback-parent/1.1.8/logback-parent-1.1.8.pom
Downloaded: https://repo.maven.apache.org/maven2/ch/qos/logback/logback-parent/1.1.8/logback-parent-1.1.8.pom (0 B at 0 B/s)
Downloading: https://dl.bintray.com/jerady/maven/ch/qos/logback/logback-core/1.1.8/logback-core-1.1.8.pom
Downloading: https://repo.maven.apache.org/maven2/ch/qos/logback/logback-core/1.1.8/logback-core-1.1.8.pom
Downloaded: https://repo.maven.apache.org/maven2/ch/qos/logback/logback-core/1.1.8/logback-core-1.1.8.pom (0 B at 0 B/s)
Downloading: https://dl.bintray.com/jerady/maven/org/fuin/ext4logback/0.2.0/ext4logback-0.2.0.jar
Downloading: https://repo.maven.apache.org/maven2/org/fuin/ext4logback/0.2.0/ext4logback-0.2.0.jar
Downloaded: https://repo.maven.apache.org/maven2/org/fuin/ext4logback/0.2.0/ext4logback-0.2.0.jar (0 B at 0 B/s)
[INFO]
[INFO] --- exec-maven-plugin:1.6.0:java (default-cli) @ ext4logback-example ---
[WARNING]
java.lang.ClassNotFoundException: org.fuin.ext4logback.example.ExampleApp
        at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
        at org.codehaus.mojo.exec.ExecJavaMojo$1.run(ExecJavaMojo.java:270)
        at java.lang.Thread.run(Thread.java:748)
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 7.992 s
[INFO] Finished at: 2018-07-20T09:31:42+02:00
[INFO] Final Memory: 10M/102M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.codehaus.mojo:exec-maven-plugin:1.6.0:java (default-cli) on project ext4logback-example: An exception occured while executing the Java class. org.fuin.ext4logback.example.ExampleApp -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException
```

```
$ java -version
java version "1.8.0_161"
Java(TM) SE Runtime Environment (build 1.8.0_161-b12)
Java HotSpot(TM) 64-Bit Server VM (build 25.161-b12, mixed mode)
```

```
$ mvn --version
Apache Maven 3.5.0 (ff8f5e7444045639af65f6095c62210b5713f426; 2017-04-03T21:39:06+02:00)
Maven home: C:\Java\apache-maven-3.5.0
Java version: 1.8.0_131, vendor: Oracle Corporation
Java home: C:\Program Files\Java\jdk1.8.0_131\jre
Default locale: en_GB, platform encoding: Cp1252
OS name: "windows 10", version: "10.0", arch: "amd64", family: "windows"
```

**Comment by michael-schnell** [comment]
I guess you were in the top level folder in the project when you tried to execute the example app. Just change into the "example" folder and run the Maven exec command there. This should work.

**Comment by dengarcia** [comment]
@DjayDev, I believe the issue comes from a dependency. If you look at the dependency hierarchy of ext4logback:0.2.0 you see that it requires logback-classic:1.1.8

![image](https://user-images.githubusercontent.com/1864772/43005108-1c7b3382-8c32-11e8-8c17-a588f7713d38.png)

But you add an explicit package logback-classic:1.2.3

**Comment by michael-schnell** [comment]
The example works fine with:
```xml
<dependencies>
	<dependency>
		<groupId>ch.qos.logback</groupId>
		<artifactId>logback-classic</artifactId>
		<version>1.2.3</version>
	</dependency>
	<dependency>
		<groupId>org.fuin</groupId>
		<artifactId>ext4logback</artifactId>
		<version>0.2.0</version>
	</dependency>
</dependencies>
```
or
```xml
<dependencies>
	<dependency>
		<groupId>ch.qos.logback</groupId>
		<artifactId>logback-classic</artifactId>
		<version>1.1.8</version>
	</dependency>
	<dependency>
		<groupId>org.fuin</groupId>
		<artifactId>ext4logback</artifactId>
		<version>0.2.0</version>
	</dependency>
</dependencies>
```
or even
```xml
<dependencies>
	<dependency>
		<groupId>org.fuin</groupId>
		<artifactId>ext4logback</artifactId>
		<version>0.2.0</version>
	</dependency>
</dependencies>
```

All three variants work as expected.

Can you run the example? Does it only fail in your own app?

The "java.lang.NoClassDefFoundError: org/slf4j/event/Level" you get actually means that SLF4J is not in the classpath or a wrong version that has no "Level" class. According to the JavaDoc the class was introduced with SLF4J 1.7.15 - If it fails in your app, maybe there is an older version somewhere in the classpath.

**Comment by dengarcia** [comment]
Hello, sorry @michael-schnell but for me the first one does not work.

From a clean environment, I clone the repo, I then move to the example folder and run:

`
mvn clean package exec:java
`
I get
SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
[WARNING]
java.lang.NoClassDefFoundError: ch/qos/logback/core/joran/spi/JoranException
        at org.fuin.ext4logback.example.ExampleApp.main(ExampleApp.java:27)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.codehaus.mojo.exec.ExecJavaMojo$1.run(ExecJavaMojo.java:282)
        at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.ClassNotFoundException: ch.qos.logback.core.joran.spi.JoranException
        at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
        ... 7 more

If I remove the reference to version 1.2.3 of logback-classic, and run the same command, then it works.

**Comment by GeCol1** [comment]
It's also ok with the modification on the pom of the example mentioned by @dengarcia 
Thanks
